### ISSUE TITLE
System.EntryPointNotFoundException when Calling DumpType

### ISSUE THREAD

**Issue by superblaubeere27** [Microsoft/LLVMSharp#75]
LLVM.DumpType(LLVM.TypeOf(lhs.Value));

```
Unhandled Exception: System.EntryPointNotFoundException: Unable to find an entry point named 'LLVMDumpType' in DLL 'libLLVM'.
   at LLVMSharp.LLVM.DumpType(LLVMTypeRef Val)
   at Goddamnfuckinglanguage.LangVisitor.VisitExpression(ExpressionContext context) in C:\Users\superblaubeere27\source\repos\Goddamnfuckinglanguage\Goddamnfuckinglanguage\LangVisitor.cs:line 98
   at Goddamnfuckinglanguage.LangVisitor.VisitReturnStatement(ReturnStatementContext context) in C:\Users\superblaubeere27\source\repos\Goddamnfuckinglanguage\Goddamnfuckinglanguage\LangVisitor.cs:line 78
   at parser.CMMParser.ReturnStatementContext.Accept[TResult](IParseTreeVisitor`1 visitor) in C:\Users\superblaubeere27\source\repos\Goddamnfuckinglanguage\Goddamnfuckinglanguage\parser\CMMParser.cs:line 489
   at Antlr4.Runtime.Tree.AbstractParseTreeVisitor`1.VisitChildren(IRuleNode node)
   at parser.CMMBaseVisitor`1.VisitStatement(StatementContext context) in C:\Users\superblaubeere27\source\repos\Goddamnfuckinglanguage\Goddamnfuckinglanguage\parser\CMMBaseVisitor.cs:line 86
   at parser.CMMParser.StatementContext.Accept[TResult](IParseTreeVisitor`1 visitor) in C:\Users\superblaubeere27\source\repos\Goddamnfuckinglanguage\Goddamnfuckinglanguage\parser\CMMParser.cs:line 332
   at Antlr4.Runtime.Tree.AbstractParseTreeVisitor`1.VisitChildren(IRuleNode node)
   at parser.CMMBaseVisitor`1.VisitBlock(BlockContext context) in C:\Users\superblaubeere27\source\repos\Goddamnfuckinglanguage\Goddamnfuckinglanguage\parser\CMMBaseVisitor.cs:line 76
   at Goddamnfuckinglanguage.LangVisitor.VisitBlock(BlockContext context) in C:\Users\superblaubeere27\source\repos\Goddamnfuckinglanguage\Goddamnfuckinglanguage\LangVisitor.cs:line 69
   at parser.CMMParser.BlockContext.Accept[TResult](IParseTreeVisitor`1 visitor) in C:\Users\superblaubeere27\source\repos\Goddamnfuckinglanguage\Goddamnfuckinglanguage\parser\CMMParser.cs:line 274
   at Antlr4.Runtime.Tree.AbstractParseTreeVisitor`1.Visit(IParseTree tree)
   at Goddamnfuckinglanguage.LangVisitor.VisitMethod(MethodContext context) in C:\Users\superblaubeere27\source\repos\Goddamnfuckinglanguage\Goddamnfuckinglanguage\LangVisitor.cs:line 54
   at parser.CMMParser.MethodContext.Accept[TResult](IParseTreeVisitor`1 visitor) in C:\Users\superblaubeere27\source\repos\Goddamnfuckinglanguage\Goddamnfuckinglanguage\parser\CMMParser.cs:line 168
   at Antlr4.Runtime.Tree.AbstractParseTreeVisitor`1.VisitChildren(IRuleNode node)
   at parser.CMMBaseVisitor`1.VisitFile(FileContext context) in C:\Users\superblaubeere27\source\repos\Goddamnfuckinglanguage\Goddamnfuckinglanguage\parser\CMMBaseVisitor.cs:line 46
   at parser.CMMParser.FileContext.Accept[TResult](IParseTreeVisitor`1 visitor) in C:\Users\superblaubeere27\source\repos\Goddamnfuckinglanguage\Goddamnfuckinglanguage\parser\CMMParser.cs:line 113
   at Antlr4.Runtime.Tree.AbstractParseTreeVisitor`1.Visit(IParseTree tree)
   at Goddamnfuckinglanguage.Program.Main(String[] args) in C:\Users\superblaubeere27\source\repos\Goddamnfuckinglanguage\Goddamnfuckinglanguage\Program.cs:line 27```

**Comment by tannergooding** [comment]
This issue is out of date and should be resolved with the latest binaries we produce.
